### ISSUE TITLE
NoSuchElementException when importing .fit file

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#137]
@FJBDev 

This error occures in your code

https://github.com/wolfgang-ch/mytourbook/blob/dc4d27ddfd7f7242f65383c4fbe49538b9377d3b/bundles/net.tourbook.device.garmin.fit/src/net/tourbook/device/garmin/fit/listeners/MesgListener_Session.java#L133

java.util.NoSuchElementException: No value present
	at java.util.OptionalDouble.getAsDouble(OptionalDouble.java:118)
	at net.tourbook.device.garmin.fit.listeners.MesgListener_Session.onMesg(MesgListener_Session.java:133)
	at com.garmin.fit.MesgBroadcaster.onMesg(MesgBroadcaster.java:1220)
	at com.garmin.fit.Decode.resume(Decode.java:403)
	at com.garmin.fit.Decode.read(Decode.java:348)
	at com.garmin.fit.Decode.read(Decode.java:343)
	at com.garmin.fit.MesgBroadcaster.run(MesgBroadcaster.java:308)
	at net.tourbook.device.garmin.fit.FitDataReader.processDeviceData(FitDataReader.java:598)
	at net.tourbook.importdata.RawDataManager.importRawData_10(RawDataManager.java:1608)
	at net.tourbook.importdata.RawDataManager.access$8(RawDataManager.java:1558)
	at net.tourbook.importdata.RawDataManager$5.run(RawDataManager.java:1471)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:55)
	at net.tourbook.importdata.RawDataManager.importRawData(RawDataManager.java:1428)
	at net.tourbook.importdata.RawDataManager$7.run(RawDataManager.java:1942)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by FJBDev** [comment]
Can you provide me a file so that I can reproduce this error ?

Thanks

**Comment by FJBDev** [comment]
That's one of the reason why I like unit tests (and why I implemented some for the Suunto 9 import) as they can help avoid those situations and in the end save time.
