### ISSUE TITLE
Exception when saving a tour

### ISSUE THREAD

**Issue by FJBDev** [wolfgang-ch/mytourbook#243]
It's the 2nd or 3rd time i see this exception when using the 20.8 release and saving a tour.
I have no scenario to consistently duplicate it.

```
org.eclipse.core.commands.ExecutionException: Error executing 'command.net.tourbook.tour.SaveTour': java.lang.ArrayIndexOutOfBoundsException: Index 786 out of bounds for length 333
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:584)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:653)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:443)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$2(KeyBindingDispatcher.java:386)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1846)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1422)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1449)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1432)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1473)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:837)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3933)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:855)
	at org.eclipse.swt.widgets.Combo.gtk_key_press_event(Combo.java:1651)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2257)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6659)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5919)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1486)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4444)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at net.tourbook.application.Application.start(Application.java:36)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.ArrayIndexOutOfBoundsException: Index 786 out of bounds for length 333
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	... 48 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 786 out of bounds for length 333
	at net.tourbook.ui.views.tourCatalog.TourCatalogView_ReferenceTour$3.dataModelChanged(TourCatalogView_ReferenceTour.java:231)
	at net.tourbook.ui.tourChart.TourChart.updateTourChartInternal(TourChart.java:5434)
	at net.tourbook.ui.tourChart.TourChart.updateTourChart(TourChart.java:5364)
	at net.tourbook.ui.views.tourCatalog.TourCatalogView_ReferenceTour.updateChart(TourCatalogView_ReferenceTour.java:290)
	at net.tourbook.ui.tourChart.TourChartViewPart$4.tourChanged(TourChartViewPart.java:188)
	at net.tourbook.tour.TourManager.fireEvent_Final(TourManager.java:1297)
	at net.tourbook.tour.TourManager.fireEvent(TourManager.java:1274)
	at net.tourbook.ui.views.tourDataEditor.TourDataEditorView.saveTourIntoDB(TourDataEditorView.java:7882)
	at net.tourbook.ui.views.tourDataEditor.TourDataEditorView.doSave(TourDataEditorView.java:5942)
	at net.tourbook.commands.SaveTour_Handler.execute(SaveTour_Handler.java:54)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 52 more
```

**Comment by wolfgang-ch** [comment]
I created a possible fix https://github.com/wolfgang-ch/mytourbook/commit/4f69494c3f8851413f096a86fb1b106b4fe018a7

**Comment by FJBDev** [comment]
Thank you, I will let you know if I see it again when I use 20.11 as I have seen it several time these last days.

**Comment by wolfgang-ch** [comment]
This fix I did keeps any none ref tours out of the ref tour chart but setting _tourData and then run updateChart() should not cause an out of bounds exception when all is correctly setup but it was not when the exception occurred. 

So I assume that something is still not good but it is difficult to find the bug when you have not a case which you can test.

**Comment by FJBDev** [comment]
For sure it is hard to find the root cause without a consistent way to reproduce it. When it appeared, it was usually after 1h of editing tours so i think it will happen again and if I find a way to reproduce it consistently, I will let you know

**Comment by FJBDev** [comment]
I just saw this issue on 20.11.1 :-(

I will try to see if I can reproduce it with a scenario

```

org.eclipse.core.commands.ExecutionException: Error executing 'command.net.tourbook.tour.SaveTour': java.lang.ArrayIndexOutOfBoundsException: Index 2344 out of bounds for length 1317
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:584)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:653)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:443)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$2(KeyBindingDispatcher.java:386)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1846)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1422)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1449)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1432)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1473)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:837)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3933)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:855)
	at org.eclipse.swt.widgets.Combo.gtk_key_press_event(Combo.java:1651)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2257)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6659)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5919)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1486)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4444)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at net.tourbook.application.Application.start(Application.java:36)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.ArrayIndexOutOfBoundsException: Index 2344 out of bounds for length 1317
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	... 48 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2344 out of bounds for length 1317
	at net.tourbook.ui.views.tourCatalog.TourCatalogView_ReferenceTour$3.dataModelChanged(TourCatalogView_ReferenceTour.java:231)
	at net.tourbook.ui.tourChart.TourChart.updateTourChartInternal(TourChart.java:5645)
	at net.tourbook.ui.tourChart.TourChart.updateTourChart(TourChart.java:5575)
	at net.tourbook.ui.views.tourCatalog.TourCatalogView_ReferenceTour.updateChart(TourCatalogView_ReferenceTour.java:290)
	at net.tourbook.ui.tourChart.TourChartViewPart$4.tourChanged(TourChartViewPart.java:190)
	at net.tourbook.tour.TourManager.fireEvent_Final(TourManager.java:1324)
	at net.tourbook.tour.TourManager.fireEvent(TourManager.java:1301)
	at net.tourbook.ui.views.tourDataEditor.TourDataEditorView.saveTourIntoDB(TourDataEditorView.java:7920)
	at net.tourbook.ui.views.tourDataEditor.TourDataEditorView.doSave(TourDataEditorView.java:5978)
	at net.tourbook.commands.SaveTour_Handler.execute(SaveTour_Handler.java:54)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 52 more
```

**Comment by wolfgang-ch** [comment]
There are too many views which are open :-)

I think there is a problem of the syncing between the opened views and the different selection/event providers

**Comment by FJBDev** [comment]
Still seeing the issue in 20.12.0
