### ISSUE TITLE
When re-importing tours using the "between dates" is not starting and no error is displayed

### ISSUE THREAD

**Issue by FJBDev** [wolfgang-ch/mytourbook#250]
Version of MT used: main branch

Issue:
NPE happens **sometimes** when re-importing tours using the "between dates" feature

Scenario to Reproduce: 
1) Open MT
2) Open the Tourbook View
3) Re-import tours between 2 dates => it should succeed
4) Go to the calendar view and randomly select a tour
5) Go back to the tour book view and try to re-import tours with the same dates used in step 3)
=> NPE will appear

Stacktrace:

```
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:397)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:468)
	at net.tourbook.database.TourDatabase.computeAnyValues_ForAllTours(TourDatabase.java:954)
	at net.tourbook.ui.views.rawData.DialogReimportTours.doReimport(DialogReimportTours.java:583)
	at net.tourbook.ui.views.rawData.DialogReimportTours.access$16(DialogReimportTours.java:505)
	at net.tourbook.ui.views.rawData.DialogReimportTours$5.run(DialogReimportTours.java:764)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at net.tourbook.ui.views.rawData.DialogReimportTours.okPressed(DialogReimportTours.java:705)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:468)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5745)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5013)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4507)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at net.tourbook.ui.views.rawData.ActionReimportTours.run(ActionReimportTours.java:37)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5745)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5013)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4507)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:153)
	at net.tourbook.application.Application.start(Application.java:36)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.NullPointerException
	at net.tourbook.tour.TourManager.checkTourData(TourManager.java:507)
	at net.tourbook.tour.TourManager.saveModifiedTours_OneTour(TourManager.java:2553)
	at net.tourbook.tour.TourManager.saveModifiedTours(TourManager.java:2491)
	at net.tourbook.tour.TourManager.saveModifiedTour(TourManager.java:2434)
	at net.tourbook.importdata.RawDataManager.actionReimportTour_30(RawDataManager.java:1116)
	at net.tourbook.importdata.RawDataManager.reimportTour(RawDataManager.java:2042)
	at net.tourbook.ui.views.rawData.DialogReimportTours$3.computeTourValues(DialogReimportTours.java:531)
	at net.tourbook.database.TourDatabase$3.run(TourDatabase.java:902)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by wolfgang-ch** [comment]
Now that you've found 👍 the NPE, it's easy to fix it because the Display was null

![mt-display-wrong-thread](https://user-images.githubusercontent.com/1283445/99257037-a5bdc100-2816-11eb-9cf3-cfb54ffd4966.png)

but there is another issues which is not easy to fix -> why is `checkTourData()` rising an error, was your tour editor open when this error occurred?

I'll merge you last PR now and will do some code hardening that this issues may less occur.

**Comment by wolfgang-ch** [comment]
Just updated main https://github.com/wolfgang-ch/mytourbook/commit/751942c6140c189a3b9924ba5f5d1241a5c67c31 to prevent this issue

**Comment by FJBDev** [comment]
>>but there is another issues which is not easy to fix -> why is checkTourData() rising an error, was your tour editor open when this error occurred?

Correct, I have the tour data editor view opened.
I will test your commit and let you know if that fixed the issue.

**Comment by FJBDev** [comment]
@wolfgang-ch 
I confirm that your commit fixed it :+1:
