### ISSUE TITLE
ArrayIndexOutOfBoundsException when creating a reference tour

### ISSUE THREAD

**Issue by FJBDev** [wolfgang-ch/mytourbook#307]
Not sure about the scenario to reproduce the issue but this is the exception I see in my production MT after I created a reference tour:

MyTourbook Version: **20.12.0**

```
java.lang.ArrayIndexOutOfBoundsException: Index 14703 out of bounds for length 9332
	at net.tourbook.ui.views.tourCatalog.TourCatalogView_ReferenceTour$3.dataModelChanged(TourCatalogView_ReferenceTour.java:231)
	at net.tourbook.ui.tourChart.TourChart.updateTourChartInternal(TourChart.java:5685)
	at net.tourbook.ui.tourChart.TourChart.updateTourChart(TourChart.java:5615)
	at net.tourbook.ui.views.tourCatalog.TourCatalogView_ReferenceTour.updateChart(TourCatalogView_ReferenceTour.java:290)
	at net.tourbook.ui.tourChart.TourChartViewPart$4.tourChanged(TourChartViewPart.java:190)
	at net.tourbook.tour.TourManager.fireEvent_Final(TourManager.java:1337)
	at net.tourbook.tour.TourManager.fireEvent(TourManager.java:1306)
	at net.tourbook.tour.TourManager.saveModifiedTours(TourManager.java:2546)
	at net.tourbook.tour.TourManager.saveModifiedTours(TourManager.java:2467)
	at net.tourbook.ui.tourChart.action.ActionCreateRefTour.run(ActionCreateRefTour.java:85)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4953)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4446)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at net.tourbook.application.Application.start(Application.java:36)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

**Comment by wolfgang-ch** [comment]
Could not reproduce it but created a fix https://github.com/wolfgang-ch/mytourbook/commit/48b0cf33ee76851d8f31d78f892cd2cda6ac7536 which should prevent this exception

**Comment by wolfgang-ch** [comment]
Fixed
