### ISSUE TITLE
i/o error

### ISSUE THREAD

**Issue by FJBDev** [wolfgang-ch/mytourbook#317]
Not sure what lead to this exception but I saw this exception in my log on my MT production today

```
org.eclipse.swt.SWTException: i/o error
	at org.eclipse.swt.SWT.error(SWT.java:4869)
	at org.eclipse.swt.SWT.error(SWT.java:4784)
	at org.eclipse.swt.SWT.error(SWT.java:4755)
	at org.eclipse.swt.graphics.ImageLoader.getImageDataArrayFromStream(ImageLoader.java:263)
	at org.eclipse.swt.graphics.ImageLoader.load(ImageLoader.java:163)
	at de.byteholder.geoclipse.map.TileImageLoader.getTileImage(TileImageLoader.java:210)
	at de.byteholder.geoclipse.map.TileImageLoader.run(TileImageLoader.java:500)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by wolfgang-ch** [comment]
Which version are you using, the stack trace do not show the correct line in my IDE

![mt java stack trace](https://user-images.githubusercontent.com/1283445/112954221-7f058480-913e-11eb-81d2-b50668b01577.png)

**Comment by FJBDev** [comment]
I use the 21.3.0 official release

![image](https://user-images.githubusercontent.com/25235665/113011381-f9caa180-9136-11eb-996a-96d3686ed0cc.png)

**Comment by wolfgang-ch** [comment]
MT 21.3 is using Eclipse 2020-09 but the line numbers in SWT are wrong, I just checked it again but have no idea why they are wrong. 

Nevertheless, sometimes I also have image errors but have not yet cared about it. Images seems to be a critical topic in swt.

![mt wrong swt line number](https://user-images.githubusercontent.com/1283445/113096588-bc791900-91f5-11eb-9879-16c5676a07a9.png)

**Comment by FJBDev** [comment]
The line number 163 seems valid to me.
If you look at the source code [here](https://github.com/eclipse/eclipse.platform.swt/blob/fe4a78b49d7d39a1f39366ed89d93575a1aff922/bundles/org.eclipse.swt/Eclipse%20SWT/gtk/org/eclipse/swt/graphics/ImageLoader.java#L163), it seems to correspond to the call of `ImageData [] imgDataArray = getImageDataArrayFromStream(stream);`

Then the line 263 leads [here](https://github.com/eclipse/eclipse.platform.swt/blob/fe4a78b49d7d39a1f39366ed89d93575a1aff922/bundles/org.eclipse.swt/Eclipse%20SWT/gtk/org/eclipse/swt/graphics/ImageLoader.java#L263) where the exception is caught `SWT.error(SWT.ERROR_IO);`

**Comment by wolfgang-ch** [comment]
When you click on the `ImageLoader.java:163` link in your IDE, what is displayed?

**Comment by FJBDev** [comment]
> When you click on the `ImageLoader.java:163` link in your IDE, what is displayed?

![image](https://user-images.githubusercontent.com/25235665/113178368-bd1caa00-920b-11eb-8e9a-1c55ea21630a.png)

**Comment by wolfgang-ch** [comment]
You log is from the GTK (Linux) SWT plugin why the source line code number is different compared when using the Windows SWT plugin.
I tested it with a new Eclipse 2020-09 and an empty workspace and had the same issue as before, until I discovered in your link that it points to the GTK version.

**Comment by FJBDev** [comment]
> -> this could be a Linux specific issue.

It is likely but I am afraid we won't fully know until we find a scenario to reproduce it.

**Comment by wolfgang-ch** [comment]
It may be possible that an image is corrupt because an Eclipse internal method fails when loading the image

**Comment by wolfgang-ch** [comment]
>So maybe a tile issue ?
The image is loaded within the tile code but the error occurs in the image loading code. You may can find the image which causes the exception.

**Comment by wolfgang-ch** [comment]
I improved the logging in https://github.com/wolfgang-ch/mytourbook/commit/2bd8b10db53a7e632f4fa8feeffed60ba4880972 which should now display the url when this error occur
