### ISSUE TITLE
Unhandled event loop exception

### ISSUE THREAD

**Issue by FJBDev** [wolfgang-ch/mytourbook#336]
Not sure about the scenario to reproduce the issue but this is the exception I see in my production MT after I modified a tour with the Tour Data Editor View

MyTourbook Version: **[21.3.0](https://github.com/wolfgang-ch/mytourbook/releases/tag/21.3.0_2021-03-21_1644)**

This is the [method call](https://github.com/wolfgang-ch/mytourbook/blob/f5bcef1c2de4aa90633d9b622f49caf57b55231f/bundles/net.tourbook/src/net/tourbook/ui/views/tourDataEditor/TourDataEditorView.java#L9255) that triggers the SWT Exception

```
org.eclipse.swt.SWTException: Graphic is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4869)
	at org.eclipse.swt.SWT.error(SWT.java:4784)
	at org.eclipse.swt.SWT.error(SWT.java:4755)
	at org.eclipse.swt.graphics.Image.getBounds(Image.java:1012)
	at org.eclipse.ui.internal.forms.widgets.BusyIndicator.computeSize(BusyIndicator.java:83)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:698)
	at org.eclipse.ui.internal.forms.widgets.TitleRegion$TitleRegionLayout.layout(TitleRegion.java:151)
	at org.eclipse.ui.internal.forms.widgets.TitleRegion$TitleRegionLayout.layout(TitleRegion.java:138)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1815)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:1111)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:1063)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:1019)
	at org.eclipse.ui.internal.forms.widgets.TitleRegion.setText(TitleRegion.java:393)
	at org.eclipse.ui.internal.forms.widgets.FormHeading.setText(FormHeading.java:707)
	at org.eclipse.ui.forms.widgets.Form.setText(Form.java:279)
	at net.tourbook.ui.views.tourDataEditor.TourDataEditorView$94.run(TourDataEditorView.java:9255)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4510)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:166)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:368)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:468)
	at net.tourbook.ui.views.rawData.RawDataView.thread_WatchStores_Cancel(RawDataView.java:5632)
	at net.tourbook.ui.views.rawData.RawDataView.setWatcher_Off(RawDataView.java:5304)
	at net.tourbook.ui.views.rawData.RawDataView.resetEasyImport(RawDataView.java:4647)
	at net.tourbook.ui.views.rawData.RawDataView.dispose(RawDataView.java:3455)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.invalidate(CompatibilityPart.java:260)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.destroy(CompatibilityPart.java:417)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:999)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:964)
	at org.eclipse.e4.core.internal.di.InjectorImpl.uninject(InjectorImpl.java:201)
	at org.eclipse.e4.core.internal.di.Requestor.uninject(Requestor.java:176)
	at org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(ContextObjectSupplier.java:89)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:105)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.removeListenersTo(EclipseContext.java:491)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.uninject(ContextInjectionFactory.java:184)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeRemoveGui(PartRenderingEngine.java:951)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$1(PartRenderingEngine.java:870)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:865)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.removeGui(PartRenderingEngine.java:849)
	at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.disposeWidget(ElementReferenceRenderer.java:115)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeRemoveGui(PartRenderingEngine.java:942)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$1(PartRenderingEngine.java:870)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:865)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.removeGui(PartRenderingEngine.java:849)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeRemoveGui(PartRenderingEngine.java:904)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$1(PartRenderingEngine.java:870)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:865)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.removeGui(PartRenderingEngine.java:849)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeRemoveGui(PartRenderingEngine.java:904)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$1(PartRenderingEngine.java:870)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:865)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.removeGui(PartRenderingEngine.java:849)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeRemoveGui(PartRenderingEngine.java:904)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$1(PartRenderingEngine.java:870)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:865)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.removeGui(PartRenderingEngine.java:849)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeRemoveGui(PartRenderingEngine.java:904)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$1(PartRenderingEngine.java:870)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:865)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.removeGui(PartRenderingEngine.java:849)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeRemoveGui(PartRenderingEngine.java:897)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$1(PartRenderingEngine.java:870)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:865)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.removeGui(PartRenderingEngine.java:849)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeRemoveGui(PartRenderingEngine.java:904)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$1(PartRenderingEngine.java:870)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:865)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.removeGui(PartRenderingEngine.java:849)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeRemoveGui(PartRenderingEngine.java:904)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$1(PartRenderingEngine.java:870)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:865)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.removeGui(PartRenderingEngine.java:849)
	at org.eclipse.ui.internal.WorkbenchWindow.hardClose(WorkbenchWindow.java:2095)
	at org.eclipse.ui.internal.WorkbenchWindow.busyClose(WorkbenchWindow.java:1726)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$5(WorkbenchWindow.java:1751)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.WorkbenchWindow.close(WorkbenchWindow.java:1751)
	at org.eclipse.ui.internal.Workbench$11.run(Workbench.java:1108)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench.busyClose(Workbench.java:1091)
	at org.eclipse.ui.internal.Workbench.lambda$4(Workbench.java:1392)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1392)
	at org.eclipse.ui.internal.Workbench.restart(Workbench.java:2477)
	at net.tourbook.preferences.PrefPageTourTypes$12.run(PrefPageTourTypes.java:922)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4510)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:153)
	at net.tourbook.application.Application.start(Application.java:36)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by wolfgang-ch** [comment]
The root cause is a restart of MT

```
...
	at org.eclipse.ui.internal.Workbench.restart(Workbench.java:2477)
	at net.tourbook.preferences.PrefPageTourTypes$12.run(PrefPageTourTypes.java:922)
...
```

which is disposing resources. A restart of MT is always causing troubles, exceptions.

As I remember (after many many years), I found no better solution when the tour types are modified, that a restart is necessary.

**Comment by FJBDev** [comment]
I remember now that I had to restart after having modified my tour types. And then I was wondering if it was possible to not restart EVERY time a tour type is modified but it seems that you say that it's not possible.

**Comment by wolfgang-ch** [comment]
In the next version, an app restart is not necessary when the tour type image is modified, it seems that I could fix it but needs more testing.

**Comment by wolfgang-ch** [comment]
I need to correct my last comment, it's more complicated. A modified tour type image do not need a restart when only the color is modified however when the layout (e.g. rectangle or circle, border width) is modified, an app restart is needed.

When an image is painted, it's colors are painted and the alpha value for each pixel, which makes a pixel transparent or opaque or inbetween. When overwriting an existing image, I have not found a solution to overwrite also the alpha pixels, colors can be overwritten. This sounds complicated and it took me some time to find the reason why a restart is necessary. 

An app restart will be optional in the next version.

**Comment by wolfgang-ch** [comment]
I need to correct my last comment, it's more complicated. A modified tour type image do not need a restart when only the color is modified however when the layout (e.g. rectangle or circle, border width) is modified, an app restart is needed.

When an image is painted, it's colors are painted and the alpha value for each pixel, which makes a pixel transparent or opaque or inbetween. When overwriting an existing image, I have not found a solution to overwrite also the alpha pixels, colors can be overwritten. This sounds complicated and it took me some time to find the reason why a restart is necessary. 

An app restart will be optional in the next version.

**Comment by wolfgang-ch** [comment]
The UI of the tour type image pref page do now display the correct and wrong images.

**Yellow box**
Displays the old tour type image (it was a circle) which was overwritten with the new image, only the old opaque values could be overwritten

**Green box**
Displays the tour type image correctly when it's layout was modified, this is achieved by creating a new image. It would be just a lot of work that this new tour type image would be displayed correctly in the whole app -> an app restart is the quick and dirty solution.


![image](https://user-images.githubusercontent.com/1283445/118825898-5e92b480-b8bb-11eb-8ac9-89c9ae6860a7.png)

**Comment by FJBDev** [comment]
I have tested but is it normal that the "Rename" and "Delete" buttons are greyed out now ??

![image](https://user-images.githubusercontent.com/25235665/118852330-ec58aa80-b88f-11eb-8551-b36338ad026f.png)

**Comment by wolfgang-ch** [comment]
I copy&pasted code from another pref page to expand/collappse and edit the color with just one click and removed the mouse double click listener. This seems to be a typical copy&paste failure :-)

**Comment by wolfgang-ch** [comment]
> I have tested but is it normal that the "Rename" and "Delete" buttons are greyed out now ??

fixed in https://github.com/wolfgang-ch/mytourbook/commit/a8bd53be5f332463f1433b4af4e38d673000c71b

you can now also use the F2 and DEL keys for these actions

**Comment by FJBDev** [comment]
I just tested and it works again.

F2 and DEL is a great addition, I had noticed the need for those keys once. Maybe there are other menus that need it but I don't remember at the moment.
