### ISSUE TITLE
With 21.3 "easy Import" suddently wont work anymore.

### ISSUE THREAD

**Issue by telemaxx** [wolfgang-ch/mytourbook#354]
crazy, from today easy import is not working anymore.

it started with an stopped easy import:
![grafik](https://user-images.githubusercontent.com/22706487/120897537-02ec5900-c627-11eb-9d23-8da44510e321.png)

when i click 2(?) times on the start button, color changed to green:
![grafik](https://user-images.githubusercontent.com/22706487/120897568-27e0cc00-c627-11eb-866d-f38fe2bfa6d6.png)

but no files is seen. no number in the box.

i deleted all import configs, and created a new one.
did not help.

and i see the cpu is always at 25%
![grafik](https://user-images.githubusercontent.com/22706487/120897635-79895680-c627-11eb-8338-159ee6f74fc0.png)

when i switch the import view to the old view, cpu is lower:

![grafik](https://user-images.githubusercontent.com/22706487/120897673-ab022200-c627-11eb-8e73-10f298624c99.png)

inside eclipse on linux with mt 21.x everything is normal.
strange.

then i restored a older mytourbook folder, nothing different.

Tooltip looks like this:

![grafik](https://user-images.githubusercontent.com/22706487/120897838-6925ab80-c628-11eb-9f6b-37fa290e9bd9.png)

i will retest when a new version is installed.

**Comment by telemaxx** [comment]
manual import is working, but easy import is much better...

**Comment by wolfgang-ch** [comment]
Since ever, I had trouble that the USB device is recognized or not but with plugin/unplugin... I get it recognized. Have not yet figured out the correct sequence but the CPU is not 25% higher.

**Comment by FJBDev** [comment]
Do you see anything relevant in the log ?

It happens to me sometimes and just turning off and turning on again the Easy Import Manager fixes the problem. It is random though and I don't have a scenario to reproduce the issue.

**Comment by telemaxx** [comment]
> 
> 
> Do you see anything relevant in the log ?
> 

the logfiles .bak_0-9.log is filling up in seconds.

i attach the repeating lines at the end.

something about the dropbox.
so i looked in the dropbox cloud preferences.
there was not that much text as it is now after i press "authorize":
![grafik](https://user-images.githubusercontent.com/22706487/120914333-daec0c80-c69d-11eb-8b4a-1db5dfd74734.png)

after the authorize it shows more text in the preferences and everything looks good again.


!ENTRY net.tourbook.common 4 0 2021-06-06 **07:58:14.754**
!MESSAGE 
!STACK 0
java.lang.InterruptedException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:385)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:541)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:196)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:224)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:135)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:177)
	at net.tourbook.ui.views.rawData.RawDataView$53.run(RawDataView.java:5665)

!ENTRY net.tourbook.common 4 0 2021-06-06 **07:58:14.756**
!MESSAGE 
!STACK 0
java.lang.InterruptedException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:385)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:541)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:196)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:224)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:135)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:177)
	at net.tourbook.ui.views.rawData.RawDataView$53.run(RawDataView.java:5665)

!ENTRY net.tourbook.common 4 0 2021-06-06 07:58:14.758
!MESSAGE 
!STACK 0

**Comment by telemaxx** [comment]
no, as i know how to solve the problem i recovered a 3 days old backup.
as expected problem is back.

Dropbox preferences before i press authorize:

![grafik](https://user-images.githubusercontent.com/22706487/120915000-a417f580-c6a1-11eb-9bc9-35a99e79e155.png)

after authorize everything is good again and my deleted "Easy Import" Configurations are back again.

![grafik](https://user-images.githubusercontent.com/22706487/120915126-4a63fb00-c6a2-11eb-825d-ef0af2c24493.png)

**Comment by FJBDev** [comment]
Ok, that makes more sense now.
It seems that your Dropbox configuration was still using the old Oauth token method (20.8) and was never updated to the PKCE OAuth method (21.3) and hence the process was trying to get a new token but failing at every request.

**Comment by telemaxx** [comment]
i close it for now.
