### ISSUE TITLE
Unhandled event loop exception when placing the graph sliders to the borders

### ISSUE THREAD

**Issue by FJBDev** [wolfgang-ch/mytourbook#365]
When trying to place the chart sliders to the border, I see this exception

MyTourbook Version: **21.6.1**

```
java.lang.ArrayIndexOutOfBoundsException: Index 108515 out of bounds for length 108515
	at net.tourbook.data.TourData.computeAvg_Altitude(TourData.java:2854)
	at net.tourbook.tour.TourManager$6.compute(TourManager.java:3353)
	at net.tourbook.ui.views.TourChartAnalyzerView.updateUI_Values(TourChartAnalyzerView.java:1132)
	at net.tourbook.ui.views.TourChartAnalyzerView.updateUI_Runnable(TourChartAnalyzerView.java:980)
	at net.tourbook.ui.views.TourChartAnalyzerView.updateInfo(TourChartAnalyzerView.java:872)
	at net.tourbook.ui.views.TourChartAnalyzerView.onSelectionChanged(TourChartAnalyzerView.java:755)
	at net.tourbook.ui.views.TourChartAnalyzerView$3.tourChanged(TourChartAnalyzerView.java:248)
	at net.tourbook.tour.TourManager.fireEvent_Final(TourManager.java:1327)
	at net.tourbook.tour.TourManager.fireEventWithCustomData(TourManager.java:1345)
	at net.tourbook.ui.tourChart.TourChartView.fireSliderPosition(TourChartView.java:522)
	at net.tourbook.ui.tourChart.TourChartView$6.sliderMoved(TourChartView.java:452)
	at net.tourbook.chart.Chart.fireSliderMoveEvent(Chart.java:625)
	at net.tourbook.chart.ChartXSlider.moveToXXDevPosition(ChartXSlider.java:241)
	at net.tourbook.chart.ChartXSlider.moveToXXDevPosition(ChartXSlider.java:185)
	at net.tourbook.chart.ChartComponentGraph.moveSlidersToBorderWithoutCheck(ChartComponentGraph.java:7117)
	at net.tourbook.chart.Chart.onExecuteMoveSlidersToBorder(Chart.java:827)
	at net.tourbook.chart.ActionMoveSlidersToBorder.run(ActionMoveSlidersToBorder.java:33)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5831)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5092)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)

```

**Comment by wolfgang-ch** [comment]
Have you moved the sliders manually or with the action "Move Sliders to Border" ?

**Comment by FJBDev** [comment]
With the action "Move Sliders to Border"

**Comment by wolfgang-ch** [comment]
Could not verify this issue but implemented a bound checking in https://github.com/wolfgang-ch/mytourbook/commit/a6a6202603ce5148ceeca35951c08d70c64f8434 to prevent this exception
