### ISSUE TITLE
 Unhandled event loop exception when using the tour tag filter

### ISSUE THREAD

**Issue by FJBDev** [wolfgang-ch/mytourbook#373]
When using the tour tag filter, I get this error

Today was the first day that I wanted to try to discover the Photos feature in the hope of attaching photos to my tours but I think I will now experiment in Eclipse with my test database until I feel confident that it doesn't crash anymore. I think I am done using the photos feature for today :confused: 

MyTourbook Version: **21.6.1**

```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4889)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.SWT.error(SWT.java:4775)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:555)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:470)
	at org.eclipse.swt.widgets.Control.setRedraw(Control.java:5880)
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter.onTag_SelectCategory_20_AutoExpandCollapse_Runnable(SlideoutTourTagFilter.java:1995)
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter$28.run(SlideoutTourTagFilter.java:1964)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5067)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4573)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
```

```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Debian
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr
Command-line arguments:  -os linux -ws gtk -arch x86_64 -debug

```

**Comment by wolfgang-ch** [comment]
> Today was the first day that I wanted to try to discover the Photos feature in the hope of attaching photos to my tours but I think I will now experiment in Eclipse with my test database until I feel confident that it doesn't crash anymore. I think I am done using the photos feature for today 😕

I'm using the photo feature regularily without having problems

![image](https://user-images.githubusercontent.com/1283445/127960751-fc5115c1-5d89-439e-a691-9c26b9f289e2.png)

**Comment by FJBDev** [comment]
> I'm using the photo feature regularily without having problems

Maybe I found issues when using the Photos feature with Linux ?
