### ISSUE TITLE
org.hibernate.exception.GenericJDBCException: could not insert: [net.tourbook.data.TourMarker]

### ISSUE THREAD

**Issue by FJBDev** [wolfgang-ch/mytourbook#418]
When saving a tour after importing it, I get this error

MyTourbook Version: **21.9**

```
org.hibernate.exception.GenericJDBCException: could not insert: [net.tourbook.data.TourMarker]
	at org.hibernate.exception.SQLStateConverter.handledNonSpecificException(SQLStateConverter.java:126)
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:114)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:64)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2176)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2656)
	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:71)
	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:279)
	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:321)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:204)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:130)
	at org.hibernate.ejb.event.EJB3PersistEventListener.saveWithGeneratedId(EJB3PersistEventListener.java:49)
	at org.hibernate.event.def.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:154)
	at org.hibernate.event.def.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:110)
	at org.hibernate.impl.SessionImpl.firePersist(SessionImpl.java:637)
	at org.hibernate.impl.SessionImpl.persist(SessionImpl.java:629)
	at org.hibernate.engine.EJB3CascadingAction$1.cascade(EJB3CascadingAction.java:28)
	at org.hibernate.engine.Cascade.cascadeToOne(Cascade.java:292)
	at org.hibernate.engine.Cascade.cascadeAssociation(Cascade.java:240)
	at org.hibernate.engine.Cascade.cascadeProperty(Cascade.java:193)
	at org.hibernate.engine.Cascade.cascadeCollectionElements(Cascade.java:320)
	at org.hibernate.engine.Cascade.cascadeCollection(Cascade.java:266)
	at org.hibernate.engine.Cascade.cascadeAssociation(Cascade.java:243)
	at org.hibernate.engine.Cascade.cascadeProperty(Cascade.java:193)
	at org.hibernate.engine.Cascade.cascade(Cascade.java:154)
	at org.hibernate.event.def.AbstractSaveEventListener.cascadeAfterSave(AbstractSaveEventListener.java:479)
	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:357)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:204)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:144)
	at org.hibernate.ejb.event.EJB3PersistEventListener.saveWithGeneratedId(EJB3PersistEventListener.java:49)
	at org.hibernate.event.def.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:154)
	at org.hibernate.event.def.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:110)
	at org.hibernate.event.def.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:61)
	at org.hibernate.impl.SessionImpl.firePersist(SessionImpl.java:646)
	at org.hibernate.impl.SessionImpl.persist(SessionImpl.java:620)
	at org.hibernate.impl.SessionImpl.persist(SessionImpl.java:624)
	at org.hibernate.ejb.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:220)
	at net.tourbook.database.TourDatabase.saveTour_Concurrent(TourDatabase.java:2870)
	at net.tourbook.ui.views.rawData.RawDataView.saveImportedTours_20_Concurrent_OneTour(RawDataView.java:5326)
	at net.tourbook.ui.views.rawData.RawDataView.lambda$14(RawDataView.java:5286)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLTransactionRollbackException: A lock could not be obtained within the time requested
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:57)
	... 41 more
Caused by: ERROR 40XL1: A lock could not be obtained within the time requested
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.catalog.SequenceUpdater.tooMuchContentionException(Unknown Source)
	at org.apache.derby.impl.sql.catalog.SequenceUpdater.getCurrentValueAndAdvance(Unknown Source)
	at org.apache.derby.impl.sql.catalog.DataDictionaryImpl.getCurrentValueAndAdvance(Unknown Source)
	at org.apache.derby.impl.sql.execute.BaseActivation.getCurrentValueAndAdvance(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.getSetAutoincrementValue(Unknown Source)
	at org.apache.derby.impl.sql.execute.BaseActivation.getSetAutoincrementValue(Unknown Source)
	at org.apache.derby.exe.aca3b7cf1bx017dx0ae2x4b57x0000153a11303.e0(Unknown Source)
	at org.apache.derby.impl.services.reflect.DirectCall.invoke(Unknown Source)
	at org.apache.derby.impl.sql.execute.RowResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 46 more
```

**Comment by wolfgang-ch** [comment]
* Can you reproduce it ?
* Have you saved at this time only one tour or multiple tours ?

**Comment by FJBDev** [comment]
>     * Can you reproduce it ?

No

>     * Have you saved at this time only one tour or multiple tours ?

One tour only

**Comment by FJBDev** [comment]
I had to revert my database to an early backup because I couldn't delete this tour anymore.

**Comment by wolfgang-ch** [comment]
> 
> 
> I had to revert my database to an early backup because I couldn't delete this tour anymore.

Was there a message box or log entries when you couldn't delete this tour?

When there is any problem with the tour db, it's always a good idea to run the db consistency test.

**Comment by wolfgang-ch** [comment]
Info how to debug lock issues but it requires that the database is running in the server mode to run sql statements https://cwiki.apache.org/confluence/display/DERBY/LockDebugging

"It is also possible to obtain a snapshot of the lock table of a running database by executing the following statement:"
```
select * from syscs_diag.lock_table; 
```

**Comment by FJBDev** [comment]
> > I had to revert my database to an early backup because I couldn't delete this tour anymore.
> 
> Was there a message box or log entries when you couldn't delete this tour?
> 
> When there is any problem with the tour db, it's always a good idea to run the db consistency test.

Ok, I will do that if the error appears again. I was worried I had broken my database so I immediately reverted to my last working backup. Next time I will backup the "broken" database for investigation.

**Comment by FJBDev** [comment]
The error happened to me again when trying to save imported tours.

The consistency check didn't reveal anything:
![image](https://user-images.githubusercontent.com/25235665/141651223-874eb464-6723-4f6d-880d-f869226f2e08.png)

This is what the below SQL command returns (i.e: nothing)
`select * from syscs_diag.lock_table; `

![image](https://user-images.githubusercontent.com/25235665/141651310-b4c8e5aa-2f9b-4475-96bf-c16aaa9b5827.png)

**Comment by wolfgang-ch** [comment]
> This is what the below SQL command returns (i.e: nothing)
> `select * from syscs_diag.lock_table; `

Had you closed and/or reopened MT before running this sql statement?

> The error happened to me again when trying to save imported tours.

* Have you tried multiple times to save the tours, to reproduce it or could you finally save the tours?
* Another test of the db could be to compress the database which is also available in the Help menu

**Comment by FJBDev** [comment]
> Had you closed and/or reopened MT before running this sql statement?

Yes, because when I change to "Network server" in order to be able to use DBeaver, it asks to restart MT.
![image](https://user-images.githubusercontent.com/25235665/141705357-cb346bd7-ff7e-4a52-9965-d5ea8bde1535.png)


>     * Have you tried multiple times to save the tours, to reproduce it or could you finally save the tours?

I didn't try because after the exception occurred, the tours were saved.


>     * Another test of the db could be to compress the database which is also available in the Help menu

This time I backed up the database right after the lock issue. 
When I compress the database, this is what I get (I don't see anything outstanding, do you?). I used "Compress in place"

```

 
 DATABASE SIZE BEFORE COMPRESSION
=================================

                                            Used     Not Used    ALLOCATED         FREE     UNFILLED         PAGE 
 Table                                     kByte        kByte        PAGES        PAGES        PAGES         SIZE 

 DBVERSION                                     4            0            1            0            1        4,096 
 DB_VERSION_DATA                               4            0            1            0            1        4,096 
 DEVICESENSOR                                 32            0            1            0            1       32,768 
 DEVICESENSORVALUE                             4            0            1            0            1        4,096 
 TOURBIKE                                      4            0            1            0            0        4,096 
 TOURCOMPARED                                132            4           32            1            1        4,096 
 TOURDATA                                620,512       22,720       18,681          710        2,581       32,768 
 TOURDATA_TOURTAG                          1,292           20          318            5            0        4,096 
 TOURGEOPARTS                              3,824          112          928           28            9        4,096 
 TOURMARKER                                2,880            0           90            0            1       32,768 
 TOURPERSON                                    4            0            1            0            0        4,096 
 TOURPERSONHRZONE                             64            0            2            0            0       32,768 
 TOURPHOTO                                     4            0            1            0            0        4,096 
 TOURREFERENCE                                52            0           13            0            1        4,096 
 TOURTAG                                     284           20           66            5            4        4,096 
 TOURTAGCATEGORY                              16            0            4            0            1        4,096 
 TOURTAGCATEGORY_TOURTAG                      80           28           13            7            2        4,096 
 TOURTAGCATEGORY_TOURTAGCATEGORY              44            4           10            1            1        4,096 
 TOURTYPE                                      8            0            2            0            1        4,096 
 TOURWAYPOINT                                 32            0            1            0            0       32,768 


 Index

 DEVICESENSORVALUE__TOURSTARTTIME              4            0            1            0            1        4,096 
 GEOPART                                   1,936            0          484            0           47        4,096 
 HASGEODATA                                  232            0           58            0            2        4,096 
 IMAGEFILEPATHNAME                             4            0            1            0            1        4,096 
 SERIALNUMBER                                  4            0            1            0            1        4,096 
 SQL190101201023650                          320            0           80            0            1        4,096 
 SQL190101201024010                            4            0            1            0            1        4,096 
 SQL190101201024030                            4            0            1            0            1        4,096 
 SQL190101201024050                            4            0            1            0            1        4,096 
 SQL190101201024070                          200            0           50            0            1        4,096 
 SQL190101201024090                            4            0            1            0            1        4,096 
 SQL190101201024130                            4            0            1            0            1        4,096 
 SQL190101201024140                           24            0            6            0            1        4,096 
 SQL190101201024170                            4            0            1            0            1        4,096 
 SQL190101201024230                           12            0            3            0            2        4,096 
 SQL190101201024280                          344            4           85            1            2        4,096 
 SQL190101201024320                            4            0            1            0            1        4,096 
 SQL190101201024360                            4            0            1            0            1        4,096 
 SQL190101201024370                            4            0            1            0            1        4,096 
 SQL190101201024400                            4            0            1            0            1        4,096 
 SQL190101201024420                            4            0            1            0            1        4,096 
 SQL190101201024440                            4            0            1            0            1        4,096 
 SQL190305081719740                        2,516           16          625            4            7        4,096 
 SQL211114173127330                            4            0            1            0            1        4,096 
 SQL211114173127610                            4            0            1            0            1        4,096 
 STARTWEEK                                   212            0           53            0            1        4,096 
 STARTWEEKYEAR                               256            0           64            0            1        4,096 
 TOURDATA__BATTERY_PERCENTAGE_START          224            0           56            0            1        4,096 
 TOURENDTIME                                 360            0           90            0            1        4,096 
 TOURID                                    3,060            8          763            2          256        4,096 
 TOURIMPORTFILENAME                          648            0          162            0           54        4,096 
 TOURPERSON                                  320            0           80            0            0        4,096 
 TOURSTARTTIME                               340            0           85            0            1        4,096 
 TOURTAG_TAGID                               320           16           76            4            0        4,096 
 TOURTYPE                                    368            0           92            0           13        4,096 
 YEARMONTH                                   284            0           71            0            4        4,096 


 Total                                   641,320       22,952                                                     

 DATABASE SIZE AFTER COMPRESSION
================================

                                            Used     Not Used    ALLOCATED         FREE     UNFILLED         PAGE 
 Table                                     kByte        kByte        PAGES        PAGES        PAGES         SIZE 

 DBVERSION                                     8            0            2            0            1        4,096 
 DB_VERSION_DATA                               8            0            2            0            1        4,096 
 DEVICESENSOR                                 64            0            2            0            1       32,768 
 DEVICESENSORVALUE                             8            0            2            0            1        4,096 
 TOURBIKE                                      8            0            2            0            1        4,096 
 TOURCOMPARED                                 84            0           21            0            1        4,096 
 TOURDATA                                577,888            0       18,059            0            1       32,768 
 TOURDATA_TOURTAG                            252            0           63            0            1        4,096 
 TOURGEOPARTS                              1,404            0          351            0            1        4,096 
 TOURMARKER                                1,248            0           39            0            1       32,768 
 TOURPERSON                                    8            0            2            0            1        4,096 
 TOURPERSONHRZONE                             64            0            2            0            1       32,768 
 TOURPHOTO                                     8            0            2            0            1        4,096 
 TOURREFERENCE                                 8            0            2            0            1        4,096 
 TOURTAG                                     156            0           39            0            1        4,096 
 TOURTAGCATEGORY                               8            0            2            0            1        4,096 
 TOURTAGCATEGORY_TOURTAG                      12            0            3            0            1        4,096 
 TOURTAGCATEGORY_TOURTAGCATEGORY               8            0            2            0            1        4,096 
 TOURTYPE                                      8            0            2            0            1        4,096 
 TOURWAYPOINT                                 64            0            2            0            1       32,768 


 Index

 DEVICESENSORVALUE__TOURSTARTTIME              4            0            1            0            1        4,096 
 GEOPART                                     964            0          241            0            1        4,096 
 HASGEODATA                                  140            0           35            0            0        4,096 
 IMAGEFILEPATHNAME                             4            0            1            0            1        4,096 
 SERIALNUMBER                                  4            0            1            0            1        4,096 
 SQL190101201023650                          192            0           48            0            1        4,096 
 SQL190101201024010                            4            0            1            0            1        4,096 
 SQL190101201024030                            4            0            1            0            1        4,096 
 SQL190101201024050                            4            0            1            0            1        4,096 
 SQL190101201024070                          176            0           44            0            1        4,096 
 SQL190101201024090                            4            0            1            0            1        4,096 
 SQL190101201024130                            4            0            1            0            1        4,096 
 SQL190101201024140                           24            0            6            0            1        4,096 
 SQL190101201024170                            4            0            1            0            1        4,096 
 SQL190101201024230                            4            0            1            0            0        4,096 
 SQL190101201024280                          180            0           45            0            0        4,096 
 SQL190101201024320                            4            0            1            0            1        4,096 
 SQL190101201024360                            4            0            1            0            0        4,096 
 SQL190101201024370                            4            0            1            0            0        4,096 
 SQL190101201024400                            4            0            1            0            1        4,096 
 SQL190101201024420                            4            0            1            0            1        4,096 
 SQL190101201024440                            4            0            1            0            1        4,096 
 SQL190305081719740                        1,420            0          355            0            2        4,096 
 SQL211114173127330                            4            0            1            0            1        4,096 
 SQL211114173127610                            4            0            1            0            1        4,096 
 STARTWEEK                                   148            0           37            0            0        4,096 
 STARTWEEKYEAR                               148            0           37            0            0        4,096 
 TOURDATA__BATTERY_PERCENTAGE_START          148            0           37            0            1        4,096 
 TOURENDTIME                                 192            0           48            0            1        4,096 
 TOURID                                    1,148            0          287            0            0        4,096 
 TOURIMPORTFILENAME                          332            0           83            0            1        4,096 
 TOURPERSON                                  192            0           48            0            1        4,096 
 TOURSTARTTIME                               192            0           48            0            1        4,096 
 TOURTAG_TAGID                               180            0           45            0            0        4,096 
 TOURTYPE                                    192            0           48            0            1        4,096 
 YEARMONTH                                   176            0           44            0            1        4,096 


 Total                                   587,532            0                                                     

 DATABASE SIZE DIFFERENCE
=========================

                                          Before        After   Difference 
 Table                                     kByte        kByte        kByte 

 DBVERSION                                     4            8            4 
 DB_VERSION_DATA                               4            8            4 
 DEVICESENSOR                                 32           64           32 
 DEVICESENSORVALUE                             4            8            4 
 TOURBIKE                                      4            8            4 
 TOURCOMPARED                                132           84          -48 
 TOURDATA                                620,512      577,888      -42,624 
 TOURDATA_TOURTAG                          1,292          252       -1,040 
 TOURGEOPARTS                              3,824        1,404       -2,420 
 TOURMARKER                                2,880        1,248       -1,632 
 TOURPERSON                                    4            8            4 
 TOURPERSONHRZONE                             64           64            0 
 TOURPHOTO                                     4            8            4 
 TOURREFERENCE                                52            8          -44 
 TOURTAG                                     284          156         -128 
 TOURTAGCATEGORY                              16            8           -8 
 TOURTAGCATEGORY_TOURTAG                      80           12          -68 
 TOURTAGCATEGORY_TOURTAGCATEGORY              44            8          -36 
 TOURTYPE                                      8            8            0 
 TOURWAYPOINT                                 32           64           32 


 Index

 DEVICESENSORVALUE__TOURSTARTTIME              4            4            0 
 GEOPART                                   1,936          964         -972 
 HASGEODATA                                  232          140          -92 
 IMAGEFILEPATHNAME                             4            4            0 
 SERIALNUMBER                                  4            4            0 
 SQL190101201023650                          320          192         -128 
 SQL190101201024010                            4            4            0 
 SQL190101201024030                            4            4            0 
 SQL190101201024050                            4            4            0 
 SQL190101201024070                          200          176          -24 
 SQL190101201024090                            4            4            0 
 SQL190101201024130                            4            4            0 
 SQL190101201024140                           24           24            0 
 SQL190101201024170                            4            4            0 
 SQL190101201024230                           12            4           -8 
 SQL190101201024280                          344          180         -164 
 SQL190101201024320                            4            4            0 
 SQL190101201024360                            4            4            0 
 SQL190101201024370                            4            4            0 
 SQL190101201024400                            4            4            0 
 SQL190101201024420                            4            4            0 
 SQL190101201024440                            4            4            0 
 SQL190305081719740                        2,516        1,420       -1,096 
 SQL211114173127330                            4            4            0 
 SQL211114173127610                            4            4            0 
 STARTWEEK                                   212          148          -64 
 STARTWEEKYEAR                               256          148         -108 
 TOURDATA__BATTERY_PERCENTAGE_START          224          148          -76 
 TOURENDTIME                                 360          192         -168 
 TOURID                                    3,060        1,148       -1,912 
 TOURIMPORTFILENAME                          648          332         -316 
 TOURPERSON                                  320          192         -128 
 TOURSTARTTIME                               340          192         -148 
 TOURTAG_TAGID                               320          180         -140 
 TOURTYPE                                    368          192         -176 
 YEARMONTH                                   284          176         -108 


 Total                                   641,320      587,532      -53,788 
                                 

```

**Comment by wolfgang-ch** [comment]
> > Had you closed and/or reopened MT before running this sql statement?
> 
> Yes, because when I change to "Network server" in order to be able to use DBeaver, it asks to restart MT.

When you restart derby it could reset it's states, so I think this lock check may work only when you immediately run it without a db restart

>This time I backed up the database right after the lock issue.
>When I compress the database, this is what I get (I don't see anything outstanding, do you?). I used "Compress in place"

I think you will not see anything outstanding when you compress the db, I think it will "reconfigure" the tables to "fix" the lock issue. This was just an idea which needs not much time to test it.

**Comment by FJBDev** [comment]
This issue happened again on my 24.1 production today but i can't reproduce it after restarting MT

`org.hibernate.exception.GenericJDBCException: could not insert: [net.tourbook.data.TourMarker]`

**Comment by FJBDev** [comment]
This issue happened again on my 24.8 production today but i can't reproduce it after restarting MT.
Note that it was, this time, happening with the Sensors

`org.hibernate.exception.GenericJDBCException: could not insert: [net.tourbook.data.DeviceSensorValue]`

**Comment by FJBDev** [comment]
The original error with the TourMarker happened on my 24.7 production

`org.hibernate.exception.GenericJDBCException: could not insert: [net.tourbook.data.TourMarker]`
