### ISSUE TITLE
Unhandled event loop exception

### ISSUE THREAD

**Issue by FJBDev** [wolfgang-ch/mytourbook#419]
I see this the exception after re-importing several tours

MyTourbook Version: **21.9.0**

Scenario to reproduce: Can't reproduce the issue

```
java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4874)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.SWT.error(SWT.java:4779)
	at org.eclipse.swt.widgets.Dialog.error(Dialog.java:202)
	at org.eclipse.swt.widgets.Dialog.checkParent(Dialog.java:168)
	at org.eclipse.swt.widgets.Dialog.<init>(Dialog.java:131)
	at org.eclipse.swt.widgets.FileDialog.<init>(FileDialog.java:105)
	at net.tourbook.importdata.RawDataManager.actionImportFromFile(RawDataManager.java:1065)
	at net.tourbook.ui.views.rawData.RawDataView.onBrowser_LocationChanging_Runnable(RawDataView.java:4226)
	at net.tourbook.ui.views.rawData.RawDataView.lambda$6(RawDataView.java:4194)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5096)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4602)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1435)
```

**Comment by wolfgang-ch** [comment]
> It seems that the IAE happens [here](https://github.com/wolfgang-ch/mytourbook/blob/86d70c402b078247abdc603063c71d3da7c1066a/bundles/net.tourbook/src/net/tourbook/importdata/RawDataManager.java#L1065)

![image](https://user-images.githubusercontent.com/1283445/141670020-1e73407d-0313-4877-aade-6f7c437237a6.png)

Yes and this seems to be a fatal error in your system because `Display.getDefault().getActiveShell()` should always return a shell. 

`Display.getCurrent()` could return `null` but this is not called

![image](https://user-images.githubusercontent.com/1283445/141669894-c8e563f1-2541-417e-9953-957bd3cce025.png)

**Comment by FJBDev** [comment]
> Yes and this seems to be a fatal error in your system because `Display.getDefault().getActiveShell()` should always return a shell.

Indeed, it could be specific to Linux. It is the first time I see this issue.
